name: PR First Approval Action

on:
  pull_request_review:
    types:
      - submitted

jobs:
  pr_first_approval:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is already approved
        id: check_approval
        run: echo "::set-output name=approved::false"

      - name: Set Output
        if: ${{ github.event.review.state == 'approved' }}
        run: echo "::set-output name=approved::true"

      - name: Check if this is the first approval
        id: check_first_approval
        run: echo "::set-output name=first_approval::false"

      - name: Output variable
        id: output_variable
        run: echo "${{ github.event.review.state }} ${{ steps.check_first_approval.outputs.first_approval }}"

      - name: Set First Approval Output
        if: ${{ github.event.review.state == approved && steps.check_first_approval.outputs.first_approval != 'true' }}
        run: echo "::set-output name=first_approval::true"

      - name: Run on First Approval
        if: ${{ steps.check_first_approval.outputs.first_approval == 'true' }}
        run: echo "This is the first approval for the PR. The action ran successfully."
